/*
 * Copyright (C) 2015 Redjan Shabani
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package seatscalculator;

/**
 *
 * @author user
 */
public class JPanelAbout extends javax.swing.JPanel
{

	/**
	 * Creates new form JPanelAbout
	 */
	public JPanelAbout()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jLabel1 = new javax.swing.JLabel();

          jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
          jLabel1.setText("<html>\n<p color=\"red\" align=\"center\">Copyrigh (C) 2015 Redjan Shabani</p>\n<p color=\"blue\" align=\"center\">Lagja \"Pavaresia\", Rruga \"Hektor Shyti\", Skele, Vlore (AL)</p>\n<p color=\"blue\" align=\"center\">+355 69 84 93 238 | redjan.shabani@gmail.com</p>\n<p>\nThis program is free software: you can redistribute it and/or modify<br/>\nit under the terms of the GNU General Public License as published by<br/>\nthe Free Software Foundation, either version 3 of the License, or<br/>\n(at your option) any later version.\n</p>\n<p>This program is distributed in the hope that it will be useful, but<br/>\nWITHOUT ANY WARRANTY; without even the implied warranty of<br/>\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.<br/>\nSee the GNU General Public License for more details.\n</p>\n<p>\nYou should have received a copy of the GNU General Public License<br/>\nalong with this program.  If not, see <font color=\"blue\">http://www.gnu.org/licenses/</font>.\n</p>\n</html>");
          add(jLabel1);
     }// </editor-fold>//GEN-END:initComponents


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel jLabel1;
     // End of variables declaration//GEN-END:variables
}
